image: Visual Studio 2017
install:
  - ps: Install-Product node 11
  - node --version
  - npm install npm@latest -g
  - npm --version
  - npm install
build_script:
 - npm run dist
 - cd dist
 - msiexec /i "KioskDemoElectron.msi" /l*v "install.log" KIOSK_USERNAME=%username% SERVER_URL=https://ciserver TOKEN=citoken
 - type %WINDIR%\SysWOW64\powershell.log
test: off
artifacts:
  - path: .\dist\*.msi
  - path: .\dist\*.log